Riot Boss
OtagoPolytechnic/Duck pull request #108
Opened 2024-09-25 03:36 UTC by kblack89

## Describe your changes

Adding a riot boss that will use a shield and napalm attacks so the player cant always damage them and will force the player to avoid areas hit by napalm.

## Issue number and link

#107 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-10-15 23:39 UTC, kblack89 commented
This is ready for review, please give feedback on pacing of combat for boss fight. The RiotBoss scene is the one to test out on, adjust wave number and time as you wish.

2024-10-15 23:59 UTC, AlexReidNZ requested changes
This boss works well. The napalm attack and the shield don't stop when the game is paused. Fix is in a seperate comment. Bleed bug is fixed.

2024-10-15 23:59 UTC, AlexReidNZ commented on Assets/Scripts/EnemyScripts/Bosses/RiotBossBehaviour.cs
> +        while (true)
This coroutine, as well as the spawnShield one beneath need to only happen when the game is playing.
you can just add 
``if (GameSettings.gameState != GameState.InGame) { return; }``
At the start of both of them.

2024-10-17 00:40 UTC, AlexReidNZ approved these changes
Looks good now, all found bugs appear to be fixed. Ready for merging.

2024-10-17 00:40 UTC, Loerad approved these changes
Looks fine. Maybe something with piercing bullets going through the shield? Not mandatory if you think its better without.

2024-10-17 00:56 UTC, merged