UI Refactor
OtagoPolytechnic/Duck pull request #33
Opened 2024-08-01 23:04 UTC by Loerad

Hello

I have refactor most of the UI to the new system. For all new UI we should use the UI Toolkit, which if you need help just ask me.

I would like some feedback on font sizes and the color of text as I am unsure if I am happy with them, and of course any issues you come across.

The elements refactored are the HUD while playing the game, the main menu, the item panel (WIP), tutorial (WIP) and game over screen (WIP). I will not be refactoring the UI for the highscore system as I think that will be a too big of a job, I don't fully understand the code and we may be refactoring that whole system later on.

2024-08-05 01:47 UTC, kblack89 requested changes
There is an issue where you cannot submit a name for high score and also main menu button stops working in the score screen

2024-08-05 02:07 UTC, AlexReidNZ approved these changes
The new UI using the UI toolkit looks and functions great.

2024-08-05 08:22 UTC, Loerad commented on Assets/Scripts/GameManager.cs
> +        SceneManager.LoadScene("UIRemaster");
This will happen in staging

2024-08-05 08:23 UTC, Loerad commented
> There is an issue where you cannot submit a name for high score 

This issue is something that is not being solved in this branch

> main menu button stops working in the score screen

This has been resolved

2024-08-06 03:46 UTC, PBWiseman requested changes
New UI looks great! Well done learning and implementing the new system. The game over screen is currently set to visible by default so it shows up when loading the level. Once that is fixed, I am happy for this to be merged

2024-08-07 00:27 UTC, PBWiseman approved these changes

2024-08-07 00:28 UTC, kblack89 approved these changes
All previous issues have been resolved so this is good to go and the new code make sense and I cant see any apparent issues

2024-08-07 00:34 UTC, merged