Boss Bomb attack
OtagoPolytechnic/Duck pull request #74
Opened 2024-08-29 02:16 UTC by kblack89

Boss Bomb attack being merged into Boss scaling branch

2024-09-02 03:50 UTC, kblack89 commented
This is ready for review.

2024-09-03 00:34 UTC, AlexReidNZ requested changes
The new boss behaviour is really cool, the bombs work as expected and are fun to fight. A couple minor things I noticed:
* The EnemyBoss1 prefab is not assigned to the spawner, there is an empty slot
* The EnemyBoss1 prefab has a doubled fire rate compared to the other bomb boss, it shoots really fast.

2024-09-03 00:34 UTC, AlexReidNZ commented on Assets/Scripts/EnemyScripts/EnemyExplosion.cs
> +            Destroy(gameObject);
I would maybe not destroy the explosion here, as if you get hit by the explosion when it explodes, it gets destroyed instantly and you can't see the explosion that damaged you. The explosions are short enough that we probably won't need to worry about the player walking in and out of it and taking damage more than once, but if you wanted to fix that you could disable the collider when it damages the player (see melee enemy attack).

2024-09-04 00:05 UTC, kblack89 commented
I have made the requested changes and tested out. This is ready for re-review.

2024-09-04 01:16 UTC, AlexReidNZ approved these changes
After removing the redundant code, this is much more suitable for merging.

2024-09-04 02:03 UTC, PBWiseman approved these changes
I love the boss design! After the boss mechanics change we discussed in person, I am happy for this to be merged

2024-09-04 02:21 UTC, Loerad approved these changes
We will remove the debug.logs from the script in staging

2024-09-04 02:21 UTC, merged