Terminal and Commands
OtagoPolytechnic/Duck pull request #75
Opened 2024-08-30 10:20 UTC by Loerad

This PR adds the Terminal Window and Commands

The terminal is activated with F1 and you can use "help" to find available commands from there. 

This should help us going further test things and also break things if we wish.

Current commands:
```
"setweapon {weaponName}     | will set player weapon to weapon given. Accepted values: pistol, dualpistol, shotgun, sniper, machinegun, rocket, sword" 
"giveitem {itemID} {amount} | will give an item or multiple from the item list to the player (will not add to list of items the player has)"
"setstat {stat} {value}     | sets the stat specified to the value given. Accepted stats: damage, crit, maxhealth, firedelay, movespeed, critdamage"
"setwave {waveNo.}          | sets the next wave to the specified number"
"skipwave                   | will set the timer to 0, skipping the wave you are on"
"godmode {bool}             | gives the player god mode. true/false"
"spawn {enemyId} {count}    | spawns an enemy with the id given and the amount given"
"cull                       | will cull all current enemies and bullets on screen"
"stopspawn {value}          | will toggle enemies or bosses from spawning. Accepted values: enemy, boss"
```
If any command seems confusing or not explained enough feel free to write a suggestion

2024-09-02 07:35 UTC, Loerad commented
PR is ready to review

2024-09-03 01:00 UTC, AlexReidNZ requested changes
All the current commands work as they are intended, togglespawn needs its name updated everywhere that isn't the help menu then will be ready for merging.

2024-09-03 11:29 UTC, PBWiseman requested changes
Terminal works great! Will make it much easier to test features. The only major issue I could find is that if you input an enemy to spawn that doesn't exist (anything over 2 at the moment) it just has an error and doesn't print anything. Also a couple of small spelling errors to fix in review comments

2024-09-03 11:29 UTC, PBWiseman commented on Assets/Scripts/Terminal/TerminalBehaviour.cs
> +                    output.text += "\nspawn {enemyID:int} {count:int}\n\nSpawns the amount of eneimes specified in count, and the type of enemy in enemyID.\n\n";
Enemies instead of eneimes

2024-09-03 11:29 UTC, PBWiseman commented on Assets/Scripts/Terminal/TerminalBehaviour.cs
> +                    output.text += "\nstopspawn {value:string}\n\nWill stop either enemies or bosses, depeding on value given, from spawning further. Does not cull current eneimes, ues \"cull\" to do
Use instead of ues, enemies instead of eneimes, depending instead of depeding

2024-09-03 23:56 UTC, Loerad commented on Assets/Scripts/Terminal/TerminalBehaviour.cs
> +    private void StopSpawn(string choice)
fixed

2024-09-04 01:15 UTC, PBWiseman approved these changes
All issues addressed. Good to merge

2024-09-04 01:17 UTC, AlexReidNZ approved these changes
Requested changes made, good for merge.

2024-09-04 02:02 UTC, merged