ShotGun Boss
OtagoPolytechnic/Duck pull request #92
Opened 2024-09-10 02:23 UTC by kblack89

## Describe your changes

This is a boss that will use shotgun attacks and a jump attack to combat against. Also will be adding in the Bosses code to inherit from enemy base instead of Boss behavior script.

## Issue number and link

Issue #85 
Issue #81 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-09-11 02:44 UTC, kblack89 commented
I have added the Multiple bullets code, next I will work on the shadow attack and boss spawning refactor to stop bosses repeating

2024-09-11 02:56 UTC, kblack89 commented
I have refactored the boss spawning to make a random list and go down the list to avoid the occasional boss spawning a second time during a game.

2024-09-16 01:15 UTC, AlexReidNZ requested changes
This is looking good so far! The boss pointer arrow is very helpful and works exactly as intended. The shotgun boss is also looking very good, although there are a couple of issues with the jump attack:
* The shockwave is really big, much bigger than the shadow indicates. I think it would be better if it was slightly smaller and/or the shockwave size matched the shadow size so you can tell where it will hit you.
* You can damage the boss while it is jumping by shooting at the position it jumped from. You need to disable collision for the boss during the jump attack.

2024-09-16 01:53 UTC, kblack89 commented
The Boss now has its colliders turned off upon shadow jump attack. This will solve the issue of the boss taking damage during this attack

2024-09-17 06:23 UTC, kblack89 commented
This should be ready for review.

2024-09-17 11:01 UTC, PBWiseman approved these changes
Boss is looking good! The shockwave should probably have the duration reduced so the player is less likely to walk into it afterward, especially since it doesn't really need to be a persistent damage field, but other than that I'm happy for this to be merged.

2024-09-17 21:54 UTC, AlexReidNZ requested changes
This boss works as intended and feels fair and fun to fight. Just some small code cleanup, then this is ready for merge.

2024-09-17 21:54 UTC, AlexReidNZ commented on Assets/Scripts/EnemyScripts/Shockwave.cs
> +        shockwaveDamage = 30 + (GameSettings.waveNumber / 5) * 5;
This is the same as 30 + GameSettings.waveNumber
IF this is intentional it can be simplified, otherwise it needs to be fixed.

2024-09-17 21:54 UTC, AlexReidNZ commented on Assets/Scripts/EnemyScripts/Shockwave.cs
> +    public void InitializeBullet(GameObject player, int damage, bool isShotgun, float angleOffset = 0f)
This method is unused, it can be deleted.

2024-09-17 21:54 UTC, AlexReidNZ commented on Assets/Scripts/EnemyScripts/Shockwave.cs
> +        else if (other.gameObject.CompareTag("Player") && playerHit == true)
This else if does nothing, it can be removed.

2024-09-17 21:54 UTC, AlexReidNZ commented on Assets/Scripts/EnemyScripts/Bosses/ShotgunBossBehaviour.cs
> +        else if (attackCooldown <= 0 && !isJumping && resumptionDelayTimer <= 0)
This should probably be done in HandleAttack, not HandleMovement

2024-09-17 21:54 UTC, AlexReidNZ commented on Assets/Scripts/EnemyScripts/Bosses/ShadowAttack.cs
> +        if (shadowShockwavePrefab)
These if statements are formatted wrong, they have no {}.
I don't think they are doing anything.

2024-09-17 22:53 UTC, kblack89 commented
I have added in the changes to the code review issues and requests

2024-09-18 00:35 UTC, AlexReidNZ approved these changes
Requested changes made, ready for merge.

2024-09-18 00:59 UTC, Loerad approved these changes
New boss looks good, like the design, we can change the boss order in staging

2024-09-18 01:10 UTC, merged