Skills
OtagoPolytechnic/Duck pull request #95
Opened 2024-09-14 05:38 UTC by Loerad

## Describe your changes

This PR adds the skills dash, decoy and vanish as well as the menu for clicking the skills before the game starts.

![image](https://github.com/user-attachments/assets/197ce349-47b6-4c37-b704-c032c2a814b9)
This is a mockup of the skills screen with the images I made in Krita by tracing some stock images of ducks.

I have also added a command to change the currently active skill and fixed the togglespawn command feedback to be helpful now.

## Issue number and link

#10 
#83 
#87 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-09-15 14:35 UTC, Loerad commented
Pr is ready to review

2024-09-17 03:38 UTC, AlexReidNZ approved these changes
Skills function well, are fun to use and have clear visuals. Ready for merge. 

We should maybe consider starting cooldowns when the skill ends rather than when it starts (matters more for vanish as the duration is quite long).

2024-09-17 04:18 UTC, PBWiseman requested changes
Very good feature. The only bug I could find is that when there is a decoy down and you walk into a bullet not fired at you the bullet just pushes you around. The dog bites will damage you but I assume this is intentional.

On the balance end I agree with the comment about the cooldown starting at the end of the duration making more sense. 

For the dash did we end up deciding that it shouldn't have any invulnerability frames? If so the wording over the description should be changed to remove the word dodge.

Couple other things that might be personal preference. I think that movemode for the dashing feels a lot better but we should consider having the stand still dash use mouse mode. Always dashing upwards for that feels odd.

Vanish and Decoy both feel good. They feel quite strong, but I don't think that's an issue. The only other thing is considering if there should be something to identify which key to press next to the button or if that just being in settings is fine?

2024-09-17 06:05 UTC, Loerad commented
Fixing, the cooldown starting after the duration has ended. I have made it so dashing with no input does nothing and does not consume the dash. I will add some I-frames to the dash. I will have a look at fixing the decoy bullet issue, I may make it destroy the bullets it touches

2024-09-17 06:34 UTC, Loerad commented
Ready for re-review

2024-09-17 22:17 UTC, Loerad commented on Assets/Scripts/EnemyScripts/Bosses/BossBullet.cs
> +                player.GetComponent<PlayerStats>().ReceiveDamage(bulletDamage);
Change to other.Get...

2024-09-18 00:26 UTC, PBWiseman approved these changes
Issues fixed. Happy for this to be merged

2024-09-18 00:34 UTC, kblack89 approved these changes
After playtesting this out multiple times it works well with no apparent issues. The code looks good and makes sense and is nice and clean.

2024-09-18 01:27 UTC, merged